<?php

function stat_panel_plugins() {
  $plugins['stat'] = array(
    'requires' => '', 
    'excludes' => '',
    'access' => '', 
    'description' => 'Статистика по опыту и умениям',
    'weight' => 6, 
    'apply' => array(
      '/me/' => array(
        'stat_update_personal' => 'stat.personal.js', 
        'stat_draw_main_counters' => 'stat.personal.js', 
        'stat_check_update_achievements' => 'stat.js', 
      ),
      '/info.php' => array(
        'stat_update_info_personal' => 'stat.personal.js', 
        'stat_draw_info_counters' => 'stat.personal.js', 
      ),
      '/info.ach.php' => array(
        'stat_update_achievements' => 'stat.ach.js', 
        'stat_draw_achievements' => 'stat.ach.js', 
      ),
    ), 
    'event' => array(
      'stat_ach' => array(
        'callback' => 'stat_get_achievements',
        'file' => 'stat.ach.js', 
        'local' => TRUE,
      ),
    ),
  );
  return $plugins;
}

?>