<?php

function outland_panel_plugins() {
  $plugins['outland'] = array(
    'requires' => '', 
    'excludes' => '',
    'description' => 'Модуль для Outland',
    'weight' => 5, 
    'apply' => array(
      '/walk.php' => array(
        'outland_init' => 'outland.js', 
      ),
      '/walk.op.php' => array(
        'outland_init' => 'outland.js', 
      ),
      '/walk.ep.php' => array(
        'outland_init' => 'outland.js', 
      ),
    ),
  );
  return $plugins;
}

function outland_plugin_settings($form, &$form_state, $values) {
  $form = array();
  $form['outland'] = array(
    '#type' => 'fieldset', 
    '#title' => 'Outland',
    '#collapsible' => TRUE, 
  );
//   $sets = array('' => 'Не проверять ничего');
//   global $user;
//   $result = db_query('SELECT id, name FROM {gwjs_sets} WHERE uid=%d AND enabled=1 ORDER BY weight ASC', $user->uid);
//   $i = 0;
//   while($ar = db_fetch_array($result)) {
//     $sets[$ar['id']] = ++$i . '. ' . $ar['name'];
//   }
//   $form['outland']['check_set'] = array(
//     '#type' => 'select',
//     '#title' => 'Проверять комплекты', 
//     '#options' => $sets, 
//     '#default_value' => $values['check_set'], 
//     '#description' => 'После каждого боя на ауте на панели появляется прогресс-бар, проверяющий целостность комплекта. Если комплект целый, то должна появиться зеленая галочка. Если сломан, то красный крестик', 
//   );
  $form['outland']['check_set'] = array(
    '#type' => 'select',
    '#title' => 'Проверять комплект',
    '#options' => array(
      0 => 'Не проверять', 
      1 => 'Номер 1',
      2 => 'Номер 2',
      3 => 'Номер 3',
      4 => 'Номер 4',
      5 => 'Номер 5',
    ),
    '#default_value' => isset($values['check_set'])? $values['check_set']: 0,
  );
  
  $form['outland']['sectorin'] = array(
    '#type' => 'select',
    '#title' => 'Сектор для отбытия',
    '#options' => array(
      '' => 'Нет', 
      '0' => '[G] Green Parks', 
      '1' => '[G] Failure of perl',
      '2' => '[G] Seaside walleys', 
      '3' => '[G] Sheever place',
      '4' => '[G] Red point',
      '5' => '[G] Black Brooklyn',
      '6' => '[S] Dolphin Port', 
      '7' => '[Z] Power Lost', 
      '8' => '[Z] Cygnus Base', 
      '9' => '[Z] Freedom End',
      '10' => '[Z] Energy One',
      '11' => '[Z] Grand Port',
      '13' => '[P] Palm Airport', 
    ),
    '#default_value' => isset($values['sectorin'])? $values['sectorin']: 0, 
    '#description' => 'Выберете остров, который будет автоматически выбираться при отплытии с аута (при нажатии на якорь)', 
  );
  $form['outland']['autos'] = array(
    '#type' => 'checkbox',
    '#title' => 'Автоматически отплывать, ага',
    '#default_value' => isset($values['autos'])? $values['autos']: 0, 
    '#description' => 'В сочетании с предыдущей настройкой при нажатии на якорь само отплывает ;-)', 
  );
  $form['outland']['fightas'] = array(
    '#type' => 'checkbox',
    '#title' => 'Автоматически закрывать заявку',
    '#default_value' => isset($values['fightas'])? $values['fightas']: 0, 
    '#description' => 'Автоматом закрывает заявку как только вошли', 
  );
  $form['outland']['takeas'] = array(
    '#type' => 'checkbox',
    '#title' => 'Автоматически подбирать вещи',
    '#default_value' => isset($values['takeas'])? $values['takeas']: 0, 
    '#description' => 'Автоматом подбирает предмет, как только оказываемся рядом', 
  );
  $form['outland']['highlight'] = array(
    '#type' => 'checkbox',
    '#title' => 'Подкрашивать клетки, на которые можно перейти',
    '#default_value' => isset($values['highlight'])? $values['highlight']: 1, 
    '#description' => 'Слегка затемняет фон кликабельных клеток', 
  );
  

  return $form;
}

?>