<?php

function battle_panel_plugins() {
  $plugins['battle'] = array(
    'requires' => array('battlefix'), 
    'excludes' => '',
    'access' => '', 
    'weight' => -1, 
    'description' => 'Дополнения для боев',
    'apply' => array(
      '/b0/btl.php' => array(
        'battle_fix' => 'battle.js',
        'battle_init' => 'battle.js',
      ),
      '/b0/b.php' => array(
        'battle_init' => 'battle.js',
      ),
      '/warlog.php' => array(
      
      ),
    ),
  );
  return $plugins;
}

function battle_plugin_settings($form, &$form_state, $values) {
  $form = array();
  $form['battle'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE, 
    '#title' => 'Бои', 
  );
  $form['battle']['wartime_s'] = array(
    '#title' => 'Частота обновления данных в бою', 
    '#type' => 'select',
    '#options' => array(
      '' => 'нет', 
      10 => '10 сек', 
      15 => '15 сек', 
      20 => '20 сек', 
      25 => '25 сек', 
      30 => '30 сек', 
      35 => '35 сек', 
      40 => '40 сек', 
    ),
    '#description' => 'Из-за какого-то непонятного бага в игре, у большинства игроков таймаут обновления данных в бою стал 50 секунд и в настройках не изменяется, поэтому специально была сделана эта опция, которая обновляет данные в обход основных', 
    '#default_value' => isset($values['wartime_s'])? $values['wartime_s']: 15, 
  );
  $form['battle']['battle_moves'] = array(
    '#type' => 'checkbox', 
    '#default_value' => isset($values['battle_moves'])? $values['battle_moves']: 1,
    '#title' => 'Отмечать игроков, сделавших ход',
    '#description' => 'Создает избыточный трафик, т.к. это почти то же самое, если бы вы открывали вручную страницу обычного боя и смотрели кто походил а кто нет', 
  );
  $form['battle']['indexes'] = array(
    '#type' => 'checkbox', 
    '#default_value' => isset($values['indexes'])? $values['indexes']: 1,
    '#title' => 'Добавлять порядковые номера противникам',
    '#description' => 'Добавляет к списку противников справа их порядковые номера как они указаны в ниспадающем списке', 
  );
  $form['battle']['advSelect'] = array(
    '#type' => 'checkbox', 
    '#default_value' => isset($values['advSelect'])? $values['advSelect']: 1,
    '#title' => 'Показывать расширенную информацию в списке выбора противника',
    '#description' => 'Если включить эту опцию, то в список выбора добавится дополнительная информация о здоровье, видимости и оружии противника.', 
  );
  $form['battle']['nobchat_m'] = array(
    '#type' => 'checkbox', 
    '#default_value' => isset($values['nobchat_m'])? $values['nobchat_m']: 0,
    '#title' => 'Не изменять боевой чат',
    '#description' => 'Отключает функционал подсветки оружия своей команде', 
  );
  $form['battle']['noplinfo'] = array(
    '#type' => 'checkbox', 
    '#default_value' => isset($values['noplinfo'])? $values['noplinfo']: 0,
    '#title' => 'Не выводить информацию об игроке',
    '#description' => 'Отключает показ доп. информации об игроке на форме (Текущий hp, урон, видимость)', 
  );
  $form['battle']['nobgen'] = array(
    '#type' => 'checkbox', 
    '#default_value' => isset($values['nobgen'])? $values['nobgen']: 0,
    '#title' => 'Не выводить генератор',
    '#description' => 'Отключает показ генератора случайных ходов', 
  );
  $form['battle']['autogen'] = array(
    '#type' => 'checkbox', 
    '#default_value' => isset($values['autogen'])? $values['autogen']: 1,
    '#title' => 'Генерировать ход',
    '#description' => 'Если эта галочка установлена, то галочка "Генерировать ход" будет автоматически выставляться в бою', 
  );
  $form['battle']['autoredo'] = array(
    '#type' => 'checkbox', 
    '#default_value' => isset($values['autoredo'])? $values['autoredo']: 0,
    '#title' => 'Запоминать ход',
    '#description' => 'Если эта галочка установлена, то галочка "Запоминать ход" будет автоматически выставляться в бою.', 
    '#suffix' => '<script type="text/javascript">
jQuery(function() {
  jQuery("#edit-autoredo").change(function() {
    if(this.checked) jQuery("#edit-autogen").removeAttr("checked");
  });
  jQuery("#edit-autogen").change(function() {
    if(this.checked) jQuery("#edit-autoredo").removeAttr("checked");
  });
});
</script>',
  );
  $form['battle']['genuniq'] = array(
    '#type' => 'checkbox', 
    '#default_value' => isset($values['genuniq'])? $values['genuniq']: 1,
    '#title' => 'Генерировать случайный ходы для обеих рук',
    '#description' => 'Если вы включите эту опцию, то при генерации случайного хода направления ударов не будут никогда совпадать (для двуруких)',
  );
  $form['battle']['nobattlepm'] = array(
    '#type' => 'checkbox', 
    '#default_value' => isset($values['nobattlepm'])? $values['nobattlepm']: 0,
    '#title' => 'Не показывать кнопку [pm]',
  );

  //print_r($form_state['bwords']);

  if(isset($values['bwords']) && empty($form_state['bwords'])) {
    $form_state['bwords'] = explode('|', $values['bwords']);
  } else if(!isset($form_state['bwords'])) {
    $form_state['bwords'] = array();
  }
  
  $form_state['bwords'][] = '';
  
  $form['battle']['bwords'] = array(
    '#type' => 'fieldset', 
    '#title' => 'Быстрые фразы', 
    '#description' => 'список с быстрыми фразами будет находиться в бою рядом с кнопкой "Написать". Сюда можно прописать фразы, которые вы говорите в каждом бою или ваши приветствия', 
    '#tree' => TRUE, 
    '#attributes' => array(
      'id' => 'bwords', 
    ),
    '#prefix' => '<div id="battle-bwords-wrapper">',
    '#suffix' => '</div>', 
  );

  foreach($form_state['bwords'] as $index => $bword) {
    $form['battle']['bwords'][$index] = array(
      '#type' => 'textfield',
      '#default_value' => $bword, 
      '#attributes' => array(
        'style' => 'display: block;', 
        'class' => array('bword'), 
      ), 
    );
  }
  $form['battle']['bwords']['add'] = array(
    '#type' => 'button',
    '#value' => 'Добавить', 
    '#ajax' => array(
      'callback' => 'battle_add_bword',
      'wrapper' => 'battle-bwords-wrapper',
    ),
//     '#attributes' => array(
//       'onclick' => '$("#bwords .form-submit").before($("#bwords .form-item:last").clone().find("input").val("")); return false;', 
//     ), 
    '#description' => 'чтобы удалить строку, оставьте её пустой', 
  );
  return $form;
}

function battle_add_bword($form, $form_state) {
  //print_r($form['battle']['bwords']);
 // print_r($form_state);
  return $form['battle']['bwords'];
}

function battle_plugin_settings_save(&$data) {
  $bwords = array_values($data['bwords']);
  foreach($bwords as $i => $bword) {
    if(!$bword) { unset($bwords[$i]); continue; }
    $bwords[$i] = htmlspecialchars($bword);
  }
  $data['bwords'] = implode('|', $bwords);
}
?>