<?php

function npc_panel_plugins() {
  $plugins['npc'] = array(
    'requires' => '', 
    'excludes' => '',
    'description' => 'Модуль для NPC',
    'weight' => 4, 
    'apply' => array(
      '/npc.php' => array(
        'npc_updStatus' => 'npc.js', 
      ),
      
      '/warlog.php' => array(
        'ncp_warlogCheck' => 'npc.js', 
      )
    ), 
    'event' => array(
      'npc_battleend' => array(
        'file' => 'npc.js', 
        'callback' => 'npc_battleEnd', 
        'local' => TRUE, 
      ),
    ),
  );
  return $plugins;
}

function npc_menu() {
  $items = array();
  $items['npc/updateloc'] = array(
    'title' => 'NPC Update Locations',
    'callback' => 'npc_updateloc',
    'access' => TRUE,
    'type' => MENU_CALLBACK
  );
  return $items;
}

function npc_updateloc($key) {
  if($key != variable_get('npc_bot_key', '')) {
    die('Ата-тат!');
  }
  set_time_limit(600);
  require_once(drupal_get_path('module', 'gwbot') . '/gwbot.class');
  $botname = 'GWPanel Bot'; //variable_get('gwbot_guest_bot', '');
  if(!$botname) die('No bot specified');
  $bot = new GWBot($botname);
  $npc_list = array(
    1 => 'Smokie Canablez',
    2 => 'Hempy Trown',
    3 => 'Rusty Reefer',
    4 => 'Kenny Buzz',
    5 => 'Yoshinori Watanabe',
    6 => 'Donnie Ray',
    7 => 'Rony James',
    8 => 'Ricardo Gonzalez',
    9 => 'Tommy Morales', 
    10 => 'Inamoto Kanushi',
    11 => 'Tony Brandino', 
    12 => 'John Moretti', 
    16 => 'Takeshi Yamagata',
    17 => 'Michael Doyle', 
    18 => 'Alfonso Morales',
    19 => 'Roy Fatico',
    20 => 'Giovanni Greco',
  );
  $npc_locations = array();
  foreach($npc_list as $id => $name) {
    $page = $bot->get('http://www.ganjawars.ru/npc.php?id=' . $id);
    if($page && preg_match('/map.php\?sx=([0-9]+)&sy=([0-9]+)[^>]+>([^<]+)<\/a>/', $page, $matches)) {
      $npc_locations[$id] = array(
        'coords' => $matches[1] . 'x' . $matches[2],
        'name' => $matches[3], 
      );
    }
  }
  if(!file_put_contents(drupal_get_path('module', 'npc') . '/locations.js', '__panel.npcLocations = ' . drupal_to_js($npc_locations) . '; __panel.npcUpdateLocations(); ')) die('Не удалось записать в файл');
  die('Успешно обновлено ' . count($npc_locations) . ' NPC');
}

function npc_panel_widgets() {
  $z_npcs = array(
    1 => 'Smokie Canablez',
    4 => 'Kenny Buzz', 
    5 => 'Yoshinori Watanabe', 
    7 => 'Rony James', 
    9 => 'Tommy Morales',
    11 => 'Tony Brandino',
  );
  $g_npcs = array(
    2 => 'Hempy Trown',
    3 => 'Rusty Reefer',
    6 => 'Donnie Ray', 
    8 => 'Ricardo Gonzalez', 
    10 => 'Inamoto Kanushi', 
    12 => 'John Moretti', 
  );
  $p_npcs = array(
    16 => 'Takeshi Yamagata',
    17 => 'Michael Doyle', 
    18 => 'Alfonso Morales', 
    19 => 'Roy Fatico', 
    20 => 'Giovanni Greco', 
  );
  return array(
    'npc_z' => array(
      'title' => 'NPC [Z]',
      'configure' => TRUE,
      'config_params' => array('friends', 'enemies', 'undress', ),
      'config_types' => array('checkboxes', 'checkboxes', 'checkbox', ),
      'config_titles' => array('Друзья', 'Враги', 'Раздеваться перед началом разговора :)'),
      'config_values' => array($z_npcs, $z_npcs, 0),
      'callback' => 'npc_widget',
      'arguments' => array(2),
      'file' => 'npc_widgets.js', 
      'width' => 6,
      'height' => 2, 
    ),
    'npc_g' => array(
      'title' => 'NPC [G]',
      'configure' => TRUE,
      'config_params' => array('friends', 'enemies', 'undress', ),
      'config_types' => array('checkboxes', 'checkboxes', 'checkbox', ),
      'config_titles' => array('Друзья', 'Враги', 'Раздеваться перед началом разговора :)'),
      'config_values' => array($g_npcs, $g_npcs, 0),
      'callback' => 'npc_widget',
      'arguments' => array(1),
      'file' => 'npc_widgets.js', 
      'width' => 6,
      'height' => 2, 
    ),
    'npc_p' => array(
      'title' => 'NPC [P]',
      'configure' => TRUE,
      'config_params' => array('friends', 'enemies', 'undress', ),
      'config_types' => array('checkboxes', 'checkboxes', 'checkbox', ),
      'config_titles' => array('Друзья', 'Враги', 'Раздеваться перед началом разговора :)'),
      'config_values' => array($p_npcs, $p_npcs, 0),
      'callback' => 'npc_widget',
      'arguments' => array(3),
      'file' => 'npc_widgets.js', 
      'width' => 6,
      'height' => 2, 
    ),
  );
}
?>